import {
  ArrowRight,
  ArrowSquareOut,
  ArrowUp,
  ArrowsClockwise,
  BookOpen,
  ChartBar,
  ChatCircleText,
  CheckCircle,
  Coffee,
  Coins,
  Compass,
  Crown,
  Fire,
  Flask,
  GraduationCap,
  Handshake,
  Heart,
  HeartBreak,
  Lightbulb,
  Lightning,
  MapTrifold,
  Medal,
  PencilLine,
  Play,
  Scroll,
  SpeakerHigh,
  SpeakerSlash,
  Star,
  Storefront,
  Sword,
  Trophy,
  Users,
  Cards,
  DownloadSimple,
  Flag,
  FileText,
  FunnelSimple,
  Graph,
  Lock,
  MagnifyingGlass,
  MagnifyingGlassMinus,
  MagnifyingGlassPlus,
  CornersOut,
  Monitor,
  Moon,
  Plus,
  Question,
  ShieldCheck,
  SidebarSimple,
  SlidersHorizontal,
  SignOut,
  Sparkle,
  Stack,
  Sun,
  Target,
  Trash,
  UploadSimple,
  Warning,
  X,
} from "@phosphor-icons/react";
import mark from "./assets/mark.png";

// One icon family for the whole app: Phosphor, regular weight. The names below are the names that the components use.
const ICONS = {
  zoomin: MagnifyingGlassPlus,
  zoomout: MagnifyingGlassMinus,
  fit: CornersOut,
  doc: FileText,
  search: MagnifyingGlass,
  chat: ChatCircleText,
  plus: Plus,
  graph: Graph,
  sliders: SlidersHorizontal,
  target: Target,
  upload: UploadSimple,
  download: DownloadSimple,
  check: CheckCircle,
  trash: Trash,
  external: ArrowSquareOut,
  refresh: ArrowsClockwise,
  sparkle: Sparkle,
  x: X,
  logout: SignOut,
  lock: Lock,
  shield: ShieldCheck,
  help: Question,
  flag: Flag,
  layers: Stack,
  chart: ChartBar,
  alert: Warning,
  arrow: ArrowRight,
  arrowup: ArrowUp,
  filter: FunnelSimple,
  sun: Sun,
  moon: Moon,
  monitor: Monitor,
  book: BookOpen,
  sidebar: SidebarSimple,
  // the game
  trophy: Trophy,
  fire: Fire,
  heart: Heart,
  heartbreak: HeartBreak,
  bolt: Lightning,
  sword: Sword,
  crown: Crown,
  star: Star,
  compass: Compass,
  map: MapTrifold,
  cards: Cards,
  coin: Coins,
  shop: Storefront,
  coffee: Coffee,
  flask: Flask,
  write: PencilLine,
  meet: Handshake,
  people: Users,
  idea: Lightbulb,
  scroll: Scroll,
  medal: Medal,
  play: Play,
  cap: GraduationCap,
  sound: SpeakerHigh,
  mute: SpeakerSlash,
};

export function Icon({ name, size = 18, className = "", weight = "regular" }) {
  const Glyph = ICONS[name];
  if (!Glyph) return null;
  return <Glyph className={"icon " + className} size={size} weight={weight} aria-hidden="true" />;
}

// App mark: the Research Pal icon (chat bubble with a magnifier), cropped to the symbol.
export function Logo({ size = 28 }) {
  return <img className="logo" src={mark} width={size} height={size} alt="" aria-hidden="true" draggable="false" style={{ borderRadius: size * 0.225 }} />;
}
